name: Windows (MSYS2)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2

      - name: "Setup MSYS2"
        uses: msys2/setup-msys2@v2
        with:
          release: false
          install: >-
            git
            make
            python3-pip
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-doxygen
            mingw-w64-x86_64-graphviz
            msys2-w32api-runtime

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        env:
          INCLUDE: C:\msys64\usr\include\w32api
          LIB: C:\msys64\usr\lib\w32api
        run: cmake --build ${{github.workspace}}\build

      - name: Test
        working-directory: ${{github.workspace}}\build
        run: ctest -C Release
