name: code-style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y clang-format-14

      - name: Run clang-format
        run: |
          chmod +x ./code_style_check.sh
          ./code_style_check.sh
        shell: bash
