name: code-style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: pip install clang-format==18.1.8

      - name: Run clang-format
        run: ./code_style_check.sh
        shell: bash
